package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"unicode"
	"src/mapreduce"
                )

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// A word is any contiguous sequence of letters as determined by unicode.IsLetter
	words := strings.FieldsFunc(value, func(r rune) bool {
		return !unicode.IsLetter(r)
                                        })
	for _, word := range words {
		res = append(res, mapreduce.KeyValue{Key: word, Value: "1"})
                                }
	return res
                }

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	return strconv.Itoa(len(values))
                                        }

func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
                } else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
                        } else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
                                        }
		mr.Wait()
                } else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
                        }
        }
